version: '3.9'
services:
  yongdt:
    image: hyc0812/yongdt:1.0
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mysql
  mysql:
    environment:
      - MYSQL_DATABASE=docker_nest
      - MYSQL_ROOT_PASSWORD=password
      # - MYSQL_TCP_PORT: 3305
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    container_name: mysql8
    ports:
      - "3305:3306"
    image: mysql
